name: Build for pushes and PR

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v5
      with:
        dotnet-version: 5.0
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v6.0.0
      with:
        name: BBPC.dll
        path: ./BBPC/Build/Debug/BBPC.dll
    - name: Upload Dependencies
      uses: actions/upload-artifact@v6.0.0
      with:
        name: Dependencies.zip
        path: |
          ./Dlls/MonoMod.Backports.dll
          ./Dlls/MonoMod.ILHelpers.dll
        compression-level: 0
  build-extensions:
    runs-on: windows-latest
    strategy:
      matrix:
        branch: [feat/challengejar, feat/template, feat/ModManager, feat/pluslevelstudio]
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ matrix.branch }}
      - name: Setup .NET
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: 5.0
      - name: Restore dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build --no-restore
      - name: Format branch name
        uses: actions/github-script@v7
        id: branch
        with:
          script: |
            const branch = '${{ matrix.branch }}';
            return branch.split('/').join('-');
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v6.0.0
        with:
          name: BBPC-${{ steps.branch.outputs.result }}.dll
          path: ./BBPC/Build/Debug/BBPC.*.dll